name: Build and test
on:
  pull_request:
    branches:
      - master

jobs:
  build-test:
    name: Build, test and publish
    uses: HavenDV/workflows/.github/workflows/dotnet_build-test-publish.yml@main
    with:
      additional-test-arguments: '--logger GitHubActions'